### ISSUE TITLE
Configuración de Alarmas - Error de visualización de datos

### ISSUE THREAD

**Issue by asouza-git** [ltorres-therasoft/DataLoggers#12]
No se limpian los campos...
1 - Seleccionar una configuración
2 - Click en editar
3 - Modificar cualquier campo
4 - Click en cerrar pop up
5 -  Click en editar nuevamente, los campos permanecen con los valores ingresados anteriormente

**Lo mismo sucude con el boton de VIEW**

![image](https://user-images.githubusercontent.com/54724145/67034333-e156fa80-f0ed-11e9-9ba0-1c6d1f7e06aa.png)

**Comment by Matias-Cabral** [comment]
hay un problema con el refresh automatico de la grilla que no siempre se da, pero el issue esta solucionado
