### ISSUE TITLE
Mediciones - Busqueda

### ISSUE THREAD

**Issue by asouza-git** [ltorres-therasoft/DataLoggers#14]
La grilla muestra paginación aunque no se muestren resultados al filtrar en la opción de busqueda

![image](https://user-images.githubusercontent.com/54724145/67035426-064c6d00-f0f0-11e9-8d46-2283ea7d5e23.png)

**Comment by Matias-Cabral** [comment]
Se quito la búsqueda y se agrego un filtro por fechas
