### ISSUE TITLE
General - Salir del popup sin guardar muestra cambios en los datos

### ISSUE THREAD

**Issue by ltorres-therasoft** [ltorres-therasoft/DataLoggers#25]
Aunque no se guarden las modificaciones, se visualiza el cambio en la tabla. (No se cambia en la base de datos)

**Comment by lucasbarraza** [comment]
El issue se presenta en las vistas: Alarmas, Sistema Fotovoltaico, Establecimiento

**Comment by lucasbarraza** [comment]
El issue fue solucionado en las 3 vistas.
