### ISSUE TITLE
Login - Boton About tira 404

### ISSUE THREAD

**Issue by ltorres-therasoft** [ltorres-therasoft/DataLoggers#26]
![image](https://user-images.githubusercontent.com/48956728/67502398-351c9300-f65c-11e9-97df-2cafe179e400.png) 
(imagen del botón)

El botón se encuentra en la esquina superior derecha.

**Comment by lucasbarraza** [comment]
Se agregó un pagina de About básica, con texto perteneciente al documento de requisitos

**Comment by ltorres-therasoft** [comment]
![image](https://user-images.githubusercontent.com/48956728/67694432-11ba5680-f982-11e9-8568-850e3abe1c36.png)
