### ISSUE TITLE
Configuración Red/Evento/Alarmas - Agregar Datalogger ID a las entidades

### ISSUE THREAD

**Issue by asouza-git** [ltorres-therasoft/DataLoggers#8]
Dado que los requerimientos piden ABM por separado para cada entidad, necesitamos incluir dataloggerID a cada entidad de configuración

[ ] Incluir dataloggerID en todas las entidades
[ ] dataloggerID debe ser indice (no permitir duplicados)
[ ] mofidicar todos los ADM
[ ] ejecutar unit testing

**Comment by lucasbarraza** [comment]
DataloggerID agregado en todas las ABM de configuraciones. Muestra solo los disponibles, por lo que no permite duplicados.

**Comment by asouza-git** [comment]
necesita revision de un tester
